export interface Productor {
  nombre: string
  origen: string
}

export const vinosNacionales: Productor[] = [
  { nombre: 'El Monte', origen: 'Buenos Aires' },
  { nombre: 'Santé Vins', origen: 'Buenos Aires' },
  { nombre: 'Atlántica', origen: 'Buenos Aires' },
  { nombre: 'Cielos de Gualjaina', origen: 'Chubut' },
  { nombre: 'Rincón de los Leones', origen: 'Chubut' },
  { nombre: 'Bodega Costa', origen: 'Río Negro' },
  { nombre: 'Noble San Javier', origen: 'Córdoba' },
  { nombre: 'La Matilde', origen: 'Córdoba' },
  { nombre: 'Uraqui', origen: 'Jujuy' },
  { nombre: 'El Bayeh', origen: 'Jujuy' },
  { nombre: 'Viñas del Perchel', origen: 'Jujuy' },
  { nombre: 'Utama', origen: 'Salta' },
  { nombre: 'Payogasta', origen: 'Salta' },
  { nombre: '35.cinco', origen: 'San Juan' },
  { nombre: 'La Baguala', origen: 'San Juan' },
  { nombre: 'Asciende', origen: 'San Juan' },
  { nombre: 'Cara Sur', origen: 'San Juan' },
  { nombre: 'Los Dragones', origen: 'San Juan' },
  { nombre: '40/40', origen: 'Mendoza' },
  { nombre: 'AleSketini', origen: 'Mendoza' },
  { nombre: 'Alpamanta', origen: 'Mendoza' },
  { nombre: 'Les Astronautes', origen: 'Mendoza' },
  { nombre: 'Canopus', origen: 'Mendoza' },
  { nombre: 'Casa Tano', origen: 'Mendoza' },
  { nombre: 'Familia Cecchin', origen: 'Mendoza' },
  { nombre: 'Chipica', origen: 'Mendoza' },
  { nombre: 'Finca Cosmos', origen: 'Mendoza' },
  { nombre: 'Familia Cassone', origen: 'Mendoza' },
  { nombre: 'El Galponcito', origen: 'Mendoza' },
  { nombre: 'Escala Humana', origen: 'Mendoza' },
  { nombre: 'First Mistake', origen: 'Mendoza' },
  { nombre: 'Galileo', origen: 'Mendoza' },
  { nombre: 'Hermanas Gálvez', origen: 'Mendoza' },
  { nombre: 'Hanan Pacha', origen: 'Mendoza' },
  { nombre: 'La Rosendo', origen: 'Mendoza' },
  { nombre: 'Las Payas', origen: 'Mendoza' },
  { nombre: 'La Imaginación al Poder', origen: 'Mendoza' },
  { nombre: 'Leo Erazo', origen: 'Mendoza' },
  { nombre: 'Libarna', origen: 'Mendoza' },
  { nombre: 'Lucas Méndez', origen: 'Mendoza' },
  { nombre: 'Matías Michelini', origen: 'Mendoza' },
  { nombre: 'Media Naranja', origen: 'Mendoza' },
  { nombre: 'Minimales de Serrera', origen: 'Mendoza' },
  { nombre: 'Oir ese Río', origen: 'Mendoza' },
  { nombre: 'Paula Michelini', origen: 'Mendoza' },
  { nombre: 'Paso a Paso', origen: 'Mendoza' },
  { nombre: 'Pielihueso', origen: 'Mendoza' },
  { nombre: 'polOpuesto', origen: 'Mendoza' },
  { nombre: 'Presente', origen: 'Mendoza' },
  { nombre: 'Primer Horizonte', origen: 'Mendoza' },
  { nombre: 'La Ramona', origen: 'Mendoza' },
  { nombre: 'Rocamadre', origen: 'Mendoza' },
  { nombre: 'Stella Crinita', origen: 'Mendoza' },
  { nombre: 'SuperUco', origen: 'Mendoza' },
  { nombre: 'Suspiro del Viento', origen: 'Mendoza' },
  { nombre: 'Tutu', origen: 'Mendoza' },
  { nombre: 'Matías Riccitelli', origen: 'Mendoza' },
  { nombre: 'Finca Hullu', origen: 'Mendoza' },
  { nombre: 'Batallero', origen: 'Itinerante' },
  { nombre: 'Paez Paez', origen: 'Itinerante' },
]

export const vinosInternacionales: Productor[] = [
  { nombre: 'Bodega Pablo Fallabrino', origen: 'Uruguay' },
  { nombre: 'Nakkal', origen: 'Uruguay' },
  { nombre: 'Bohemian by Fiore', origen: 'Uruguay' },
  { nombre: 'Últimas parras', origen: 'Uruguay' },
  { nombre: 'Quierovino', origen: 'Uruguay' },
  { nombre: 'Pepe Moquillaza', origen: 'Perú' },
  { nombre: 'Jardín Oculto', origen: 'Bolivia' },
  { nombre: 'Cantina Mincarone', origen: 'Brasil' },
  { nombre: 'Bellaquinta', origen: 'Brasil' },
  { nombre: 'Neusa de Lucca', origen: 'Brasil' },
  { nombre: 'Vinicola Villaggio Pandini', origen: 'Brasil' },
  { nombre: 'Arte Líquida', origen: 'Brasil' },
  { nombre: 'Bodega Mariana', origen: 'Chile' },
  { nombre: 'Max Kutral', origen: 'Chile' },
  { nombre: 'Rabelo y Ravelo', origen: 'Chile' },
  { nombre: 'Cauac', origen: 'Chile' },
  { nombre: 'Plumaje de Mar', origen: 'Chile' },
  { nombre: 'Viña El Origen', origen: 'Chile' },
  { nombre: 'Vino La Joda', origen: 'Chile' },
  { nombre: 'La Vieja Parra', origen: 'Chile' },
  { nombre: 'El Rito', origen: 'Chile' },
  { nombre: 'Josef', origen: 'Italia' },
  { nombre: 'Agricola i Forestieri', origen: 'Italia' },
  { nombre: 'Bodega Cueva', origen: 'España' },
  { nombre: 'El Regreso', origen: 'España' },
]

export const afines: Productor[] = [
  { nombre: 'El Larga Vida', origen: 'Bebidas' },
  { nombre: 'Piel Spirits', origen: 'Bebidas' },
  { nombre: 'Alfonsina', origen: 'Bebidas' },
  { nombre: 'Lombroni', origen: 'Bebidas' },
  { nombre: 'Al Voleo', origen: 'Bebidas' },
  { nombre: 'Tuut', origen: 'Bebidas' },
  { nombre: 'Laurus', origen: 'Bebidas' },
  { nombre: 'Funky Barrel', origen: 'Bebidas' },
  { nombre: 'Mater Orbis', origen: 'Bebidas' },
  { nombre: 'Pülku', origen: 'Bebidas' },
  { nombre: 'Puerto Blest', origen: 'Bebidas' },
  { nombre: 'Tres café', origen: 'Bebidas' },
  { nombre: 'La Alegre Rebeldía', origen: 'Bebidas' },
  { nombre: 'Fronteras', origen: 'Bebidas' },
  { nombre: 'Polanco', origen: 'Alimentos' },
  { nombre: 'El Abascay', origen: 'Alimentos' },
  { nombre: 'Santo Padre', origen: 'Alimentos' },
  { nombre: 'Ylla', origen: 'Alimentos' },
  { nombre: 'Atelier Fuerza', origen: 'Alimentos' },
  { nombre: 'Círculo Once', origen: 'Alimentos' },
  { nombre: 'Cultivando Sur', origen: 'Alimentos' },
  { nombre: 'Las Romeas', origen: 'Alimentos' },
  { nombre: 'Miel Corneta', origen: 'Alimentos' },
  { nombre: 'Hilal', origen: 'Alimentos' },
  { nombre: 'Olivuum', origen: 'Alimentos' },
  { nombre: 'AQA', origen: 'Otrxs' },
  { nombre: 'Nadir', origen: 'Otrxs' },
  { nombre: 'Sabio', origen: 'Otrxs' },
  { nombre: 'Ruda Cósmica', origen: 'Otrxs' },
  { nombre: 'La Materia Encendida', origen: 'Otrxs' },
  { nombre: 'Colbo', origen: 'Otrxs' },
  { nombre: 'Expresión Orgánica', origen: 'Otrxs' },
]

export const gastronomia: Productor[] = [
  { nombre: 'Fornole', origen: 'Gastronomía' },
  { nombre: 'Vina', origen: 'Gastronomía' },
  { nombre: 'Anfibio', origen: 'Gastronomía' },
  { nombre: 'Fifí', origen: 'Gastronomía' },
  { nombre: 'Gordo Chanta', origen: 'Gastronomía' },
  { nombre: 'La Kitchen', origen: 'Gastronomía' },
  { nombre: 'Donnet', origen: 'Gastronomía' },
  { nombre: 'Coni Borras', origen: 'Gastronomía' },
  { nombre: 'Sofi Cicinneli', origen: 'Gastronomía' },
]
