export interface Productor {
  nombre: string
  origen: string
  ig?: string
  tipo?: string
}

export const vinosNacionales: Productor[] = [
  { nombre: '35.cinco', origen: 'San Juan', ig: '35.5vinos' },
  { nombre: '40/40', origen: 'Mendoza', ig: 'vino40cuarenta' },
  { nombre: 'AleSketini', origen: 'Mendoza', ig: 'alesketini' },
  { nombre: 'Asciende', origen: 'San Juan', ig: 'asciende.vinos' },
  { nombre: 'Atlántica', origen: 'Buenos Aires', ig: 'atlanticabodega' },
  { nombre: 'Batallero', origen: 'Itinerante', ig: 'batallerovinos' },
  { nombre: 'Bodega Costa', origen: 'Río Negro', ig: 'bodegacosta' },
  { nombre: 'Canopus', origen: 'Mendoza', ig: 'canopusvinos' },
  { nombre: 'Cara Sur', origen: 'San Juan', ig: 'carasur.barreal' },
  { nombre: 'Casa Tano', origen: 'Mendoza', ig: 'casa_tano' },
  { nombre: 'Cielos de Gualjaina', origen: 'Chubut', ig: 'cielosdegualjaina' },
  { nombre: 'Descendientes de Viticultores', origen: 'Mendoza', ig: 'descendientesdeviticultores' },
  { nombre: 'El Bayeh', origen: 'Jujuy', ig: 'bodegaelbayeh' },
  { nombre: 'El Galponcito', origen: 'Mendoza', ig: 'bodegaelgalponcito' },
  { nombre: 'El Monte', origen: 'Buenos Aires', ig: 'elmonte_' },
  { nombre: 'Escala Humana', origen: 'Mendoza', ig: 'escalahumanawines' },
  { nombre: 'Familia Cecchin', origen: 'Mendoza', ig: 'familiacecchinvinos' },
  { nombre: 'Finca Cosmos', origen: 'Mendoza', ig: 'fincacosmos' },
  { nombre: 'Finca Hullu', origen: 'Mendoza', ig: 'finca.hullu' },
  { nombre: 'First Mistake', origen: 'Mendoza' },
  { nombre: 'Galileo', origen: 'Mendoza' },
  { nombre: 'Hanan Pacha', origen: 'Mendoza', ig: 'fincahananpacha' },
  { nombre: 'Hermanas Gálvez', origen: 'Mendoza', ig: 'hermanas.galvez' },
  { nombre: 'La Baguala', origen: 'San Juan', ig: 'labaguala.barreal' },
  { nombre: 'La Imaginación al Poder', origen: 'Mendoza', ig: 'vinoslaimaginacionalpoder' },
  { nombre: 'La Matilde', origen: 'Córdoba', ig: 'lamatildebodega' },
  { nombre: 'La Rosendo', origen: 'Mendoza', ig: 'la_rosendo' },
  { nombre: 'Las Payas', origen: 'Mendoza', ig: 'finca_las_payas_' },
  { nombre: 'Les Astronautes', origen: 'Mendoza', ig: 'lesastronauteswines' },
  { nombre: 'Libarna', origen: 'Mendoza', ig: 'libarna.vinos' },
  { nombre: 'Los Dragones', origen: 'San Juan', ig: 'los.dragones.vinos' },
  { nombre: 'Lucas Méndez', origen: 'Mendoza', ig: 'lucasyamilmendez' },
  { nombre: 'Media Naranja', origen: 'Mendoza', ig: 'medianaranja.vino' },
  { nombre: 'Minimales de Serrera', origen: 'Mendoza', ig: 'fincaminimal' },
  { nombre: 'Noble San Javier', origen: 'Córdoba', ig: 'nobledesanjavier' },
  { nombre: 'Oir ese Río', origen: 'Mendoza', ig: 'oireserio' },
  { nombre: 'Paez Paez', origen: 'Itinerante', ig: 'paezpaezwines' },
  { nombre: 'Paula Michelini', origen: 'Mendoza', ig: 'descendientesdeviticultores' },
  { nombre: 'Payogasta', origen: 'Salta', ig: 'bodegapayogasta' },
  { nombre: 'Pielihueso', origen: 'Mendoza', ig: 'pielihueso' },
  { nombre: 'polOpuesto', origen: 'Mendoza', ig: 'polandsnes' },
  { nombre: 'Presente', origen: 'Mendoza', ig: 'presente.vinos' },
  { nombre: 'Primer Horizonte', origen: 'Mendoza', ig: 'primer.horizonte' },
  { nombre: 'Ramona', origen: 'Mendoza', ig: 'ramonavinos' },
  { nombre: 'Rincón de los Leones', origen: 'Chubut', ig: 'estancialosrobles.rdl' },
  { nombre: 'Rocamadre', origen: 'Mendoza', ig: 'rocamadrevinos' },
  { nombre: 'Santé Vins', origen: 'Buenos Aires', ig: 'santevins' },
  { nombre: 'Sol Naciente', origen: 'Salta', ig: 'solnacientebodega' },
  { nombre: 'Stella Crinita', origen: 'Mendoza', ig: 'stella.crinita' },
  { nombre: 'SuperUco', origen: 'Mendoza', ig: 'superuco' },
  { nombre: 'Suspiro del Viento', origen: 'Mendoza', ig: 'suspirodelviento_' },
  { nombre: 'Tutu', origen: 'Mendoza', ig: 'tutuwines' },
  { nombre: 'Uraqui', origen: 'Jujuy', ig: 'uraquiwines' },
  { nombre: 'Utama', origen: 'Salta', ig: 'utamavinosnaturales' },
  { nombre: 'V.I.N.O.', origen: 'Mendoza', ig: 'kungfuwines' },
  { nombre: 'Via Revolucionaria', origen: 'Mendoza', ig: 'matias_michelini_viticultor' },
  { nombre: 'Viñas del Perchel', origen: 'Jujuy', ig: 'vinasdelperchel' },
]

export const vinosInternacionales: Productor[] = [
  { nombre: 'Agricola i Forestieri', origen: 'Italia', ig: 'agricola_i_forestieri' },
  { nombre: 'Arte Líquida', origen: 'Brasil', ig: 'arte.liquida' },
  { nombre: 'Bellaquinta', origen: 'Brasil', ig: 'bellaquintavinhosfinos' },
  { nombre: 'Bodega Cueva', origen: 'España', ig: 'bodegacuevabymariano' },
  { nombre: 'Bodega Mariana', origen: 'Chile', ig: 'bodega.mariana' },
  { nombre: 'Bodega Pablo Fallabrino', origen: 'Uruguay', ig: 'bodegapablofallabrino' },
  { nombre: 'Bohemian by Fiore', origen: 'Uruguay' },
  { nombre: 'Cantina Mincarone', origen: 'Brasil', ig: 'cantina_mincarone' },
  { nombre: 'Cauac', origen: 'Chile', ig: 'bodegacauac' },
  { nombre: 'El Regreso', origen: 'España', ig: 'elregresowines' },
  { nombre: 'El Rito', origen: 'Chile', ig: 'elritoecoagricola' },
  { nombre: 'Jardín Oculto', origen: 'Bolivia', ig: 'jardinocultowines' },
  { nombre: 'Josef', origen: 'Italia', ig: 'josefwine' },
  { nombre: 'La Vieja Parra', origen: 'Chile', ig: 'viejaparra.vinos' },
  { nombre: 'Max Kutral', origen: 'Chile', ig: 'vinos.kutral' },
  { nombre: 'Nakkal', origen: 'Uruguay' },
  { nombre: 'Neusa de Lucca', origen: 'Brasil', ig: 'neusadelucca' },
  { nombre: 'Pepe Moquillaza', origen: 'Perú', ig: 'pepemoquillaza' },
  { nombre: 'Plumaje de Mar', origen: 'Chile', ig: 'plumajedemar' },
  { nombre: 'Quierovino', origen: 'Uruguay', ig: 'antodeambroggi' },
  { nombre: 'Rabelo y Ravelo', origen: 'Chile', ig: 'vinosraveloyrabelo' },
  { nombre: 'Últimas parras / Parcela encontrada', origen: 'Uruguay', ig: 'ultimas_parras' },
  { nombre: 'Viña El Origen', origen: 'Chile', ig: 'vinaelorigen' },
  { nombre: 'Vinicola Villaggio Pandini', origen: 'Brasil', ig: 'vinicolavillaggiopandini' },
  { nombre: 'Vino La Joda', origen: 'Chile', ig: 'vinolajoda' },
]

export const afines: Productor[] = [
  { nombre: 'Al Voleo', origen: 'Bebidas', tipo: 'Vermú', ig: 'al.voleo.vermut' },
  { nombre: 'Alfonsina', origen: 'Bebidas', tipo: 'Vermú', ig: 'alfonsina.vermut' },
  { nombre: 'AQA', origen: 'Otrxs', tipo: 'Agua' },
  { nombre: 'Atelier Fuerza', origen: 'Alimentos', tipo: 'Pan', ig: 'atelierfuerza' },
  { nombre: 'Círculo Once', origen: 'Alimentos', tipo: 'Sake y fermentos', ig: 'circulo_once' },
  { nombre: 'Colbo', origen: 'Otrxs', tipo: 'Cerámica' },
  { nombre: 'Cultivando Sur', origen: 'Alimentos', tipo: 'Picantes', ig: 'cultivandosur' },
  { nombre: 'El Abascay', origen: 'Alimentos', tipo: 'Queso', ig: 'elabascaybrandsen' },
  { nombre: 'El Larga Vida', origen: 'Bebidas', tipo: 'Gin', ig: 'el.largavidagin' },
  { nombre: 'Expresión Orgánica', origen: 'Otrxs', tipo: 'Hierbas', ig: 'nurydelcampo' },
  { nombre: 'Fronteras', origen: 'Bebidas', tipo: 'Yerba', ig: 'fronteras.yerbamate' },
  { nombre: 'Funky Barrel', origen: 'Bebidas', tipo: 'Cerveza', ig: 'funkybarrel_brewing_co' },
  { nombre: 'Hilal', origen: 'Alimentos', tipo: 'Aceite de oliva' },
  { nombre: 'La Alegre Rebeldía', origen: 'Bebidas', tipo: 'Fernet', ig: 'laalegrerebeldia' },
  { nombre: 'La Materia Encendida', origen: 'Otrxs', tipo: 'Cerámica' },
  { nombre: 'Las Romeas', origen: 'Alimentos', tipo: 'Cacao', ig: 'lasromeas' },
  { nombre: 'Laurus', origen: 'Bebidas', tipo: 'Cerveza', ig: 'cervezalaurus' },
  { nombre: 'Lombroni', origen: 'Bebidas', tipo: 'Vermú', ig: 'vermut_lombroni' },
  { nombre: 'Mater Orbis', origen: 'Bebidas', tipo: 'Kombucha', ig: 'mater.orbis' },
  { nombre: 'Miel Corneta', origen: 'Alimentos', tipo: 'Miel', ig: 'mielcorneta' },
  { nombre: 'Nadir', origen: 'Otrxs', tipo: 'Copas' },
  { nombre: 'Olivuum', origen: 'Alimentos', tipo: 'Aceite de oliva' },
  { nombre: 'Piel Spirits', origen: 'Bebidas', tipo: 'Gin', ig: 'pielspirits.co' },
  { nombre: 'Polanco', origen: 'Alimentos', tipo: 'Pan' },
  { nombre: 'Puerto Blest', origen: 'Bebidas', tipo: 'Café', ig: 'cafepuertoblest' },
  { nombre: 'Pülku', origen: 'Bebidas', tipo: 'Sidra' },
  { nombre: 'Ruda Cósmica', origen: 'Otrxs', tipo: 'Cosmética', ig: 'rudacosmica' },
  { nombre: 'Sabio', origen: 'Otrxs', tipo: 'Tabaco' },
  { nombre: 'Santo Padre', origen: 'Alimentos', tipo: 'Queso', ig: 'santopadreorganico' },
  { nombre: 'Tres café', origen: 'Bebidas', tipo: 'Café' },
  { nombre: 'Tuut', origen: 'Bebidas', tipo: 'Sidra', ig: 'tuutespumante' },
  { nombre: 'Ylla', origen: 'Alimentos', tipo: 'Queso', ig: 'quesosylla' },
]

export const gastronomia: Productor[] = [
  { nombre: 'Coni Borras', origen: 'Gastronomía', ig: 'coniborras' },
  { nombre: 'Donnet', origen: 'Gastronomía', ig: 'donnet_te_ama' },
  { nombre: 'Dudu Patisserie', origen: 'Gastronomía', ig: 'dudu_atelier_patisserie' },
  { nombre: 'Fifí', origen: 'Gastronomía', ig: 'fifialmacen' },
  { nombre: 'Fornole', origen: 'Gastronomía', ig: 'fornole' },
  { nombre: 'Gordo Chanta', origen: 'Gastronomía', ig: 'gordochantapizza' },
  { nombre: 'La Kitchen', origen: 'Gastronomía', ig: 'lakitchen.ba' },
  { nombre: 'Vina', origen: 'Gastronomía', ig: 'vina.buchette' },
]
